services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      - SIGNUPS_ALLOWED=true
    volumes:
      - ./vw-data:/data

  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy
    restart: always
    ports:
      - '80:80' # Standard HTTP
      - '81:81' # Die Admin-Oberfläche vom Proxy
      - '443:443' # HTTPS (für später)
    volumes:
      - ./proxy-data:/data
      - ./letsencrypt:/etc/letsencrypt