services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: always
    volumes:
      - ./workdir:/opt/adguardhome/work
      - ./confdir:/opt/adguardhome/conf
    ports:
      - "53:53/tcp"
      - "53:53/udp"   # DNS-Port (das Wichtigste!)
      - "3000:3000/tcp" # Erst-Einrichtung
      - "853:853/tcp"
      - "784:784/udp"
      - "3001:80/tcp"   # Dashboard (sp√§ter)