---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Gaming:
    - Minecraft:
        icon: minecraft
        href: "http://localhost" # Oder die IP deines Rechners
        server: 172.17.0.1
        port: 25565
        widget:
          type: minecraft
          url: udp://172.17.0.1:25565

